# Generated by Django 2.1.5 on 2019-09-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
